In [5]:
import tensorflow as tf
from megazord.efficientnetv2 import effnetv2_model

In [12]:
model = None

model = effnetv2_model.get_model("efficientnetv2-b0", include_top=True, pretrained=True)

AssertionError: Some objects had attributes which were not restored:
    <tf.Variable 'efficientnetv2-b0/head_1/dense_1/kernel:0' shape=(1280, 1000) dtype=float32, numpy=
array([[-1.33739710e-02, -3.07031423e-02,  9.92007181e-03, ...,
         2.89763138e-03,  3.33177671e-03,  2.22214274e-02],
       [-6.64399937e-04, -1.28317866e-02,  7.83946738e-03, ...,
         1.02046616e-02, -4.87394258e-03,  2.55316943e-02],
       [ 2.20699124e-02, -1.85675919e-04,  2.66515799e-02, ...,
         1.82150044e-02,  7.43808970e-03,  1.16038732e-02],
       ...,
       [-2.00053900e-02, -1.17983669e-04,  2.51829624e-06, ...,
         8.83238390e-03,  4.47928160e-03, -2.16219872e-02],
       [-1.00972634e-02,  2.21349113e-02, -1.64159089e-02, ...,
         1.06790140e-02,  1.94076337e-02,  2.26010606e-02],
       [ 1.03422515e-02,  2.85767503e-02, -7.02344067e-03, ...,
         5.28520346e-03,  8.39818269e-04, -7.09524751e-03]], dtype=float32)>: ['efficientnetv2-b0/head_1/dense_1/kernel']
    <tf.Variable 'efficientnetv2-b0/head_1/dense_1/bias:0' shape=(1000,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>: ['efficientnetv2-b0/head_1/dense_1/bias']
    <tf.Variable 'efficientnetv2-b0/stem_1/conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[-5.40430397e-02, -1.04924068e-02,  5.18346801e-02,
          -8.16512853e-02,  5.76012246e-02,  7.16740713e-02,
           1.30589262e-01,  7.79500082e-02, -4.85500209e-02,
          -3.12457960e-02, -5.22603318e-02,  7.77256256e-03,
          -2.08692551e-02,  1.84546873e-01,  8.35756958e-02,
          -4.96503077e-02, -3.13902716e-03,  6.86852261e-02,
           1.21581918e-02, -8.88979621e-03, -1.09300418e-02,
           9.18242261e-02,  1.07206129e-01,  2.92253532e-02,
           4.02539521e-02,  1.04922310e-01, -1.81797966e-02,
           7.24455863e-02,  9.35119987e-02,  1.77065318e-03,
          -3.88050526e-02,  5.25121018e-02],
         [-1.57075167e-01,  1.07242763e-01, -2.57828888e-02,
           2.61448175e-02,  9.69860405e-02, -5.20490520e-02,
           1.49264246e-01,  1.15763173e-01,  1.65504873e-01,
           3.08243483e-02, -3.35363522e-02, -1.93502344e-02,
           1.61428303e-01,  1.86233327e-01, -1.29712641e-01,
          -9.19619724e-02, -1.96920172e-03, -2.73359455e-02,
           1.47897944e-01, -9.19313058e-02,  3.85603532e-02,
          -1.57282650e-01, -7.07252026e-02, -6.07491843e-02,
           9.24011096e-02, -2.45086756e-02,  5.00180684e-02,
          -8.29068292e-03, -1.11029491e-01,  4.57237028e-02,
           3.61341797e-02, -2.83229724e-02],
         [ 3.05075459e-02,  3.94197479e-02,  1.48248956e-01,
          -1.06365755e-01,  1.34181768e-01,  9.54253823e-02,
           2.53083147e-02,  1.69790193e-01, -2.11990811e-02,
           3.42849605e-02,  3.50324064e-02,  1.30434871e-01,
          -9.48859602e-02, -5.84081225e-02, -3.13769653e-02,
           1.17597310e-02, -2.82397624e-02,  1.91452742e-01,
          -4.71673626e-03, -1.83606476e-01,  1.11548685e-01,
           4.21153158e-02, -2.81959362e-02,  2.84114629e-02,
          -5.98061755e-02, -4.80825007e-02,  6.49504662e-02,
          -5.14918426e-03,  2.14921311e-02,  9.01084244e-02,
           3.88934091e-02,  5.28097376e-02]],

        [[-1.93705857e-02, -5.97278625e-02,  1.19459361e-01,
          -1.10259615e-02,  1.00756049e-01,  8.64186734e-02,
          -6.30631000e-02,  9.20519158e-02,  1.13235556e-01,
           2.92405933e-02,  1.97837144e-01, -5.37002832e-02,
           2.50822753e-02, -1.49931937e-01, -1.07761338e-01,
           9.00520980e-02,  7.96878189e-02,  3.40648293e-02,
          -1.19838417e-01, -1.30007695e-02,  1.27462521e-02,
           7.04459101e-02,  1.03888229e-01,  2.72420160e-02,
          -1.98614225e-01,  1.33927297e-02,  1.30006835e-01,
          -8.33194889e-03, -7.13788271e-02,  1.06922284e-01,
           3.55542898e-02, -7.90841579e-02],
         [ 2.85964496e-02, -4.67169397e-02,  3.02016176e-02,
           4.40745726e-02,  1.80495046e-02,  1.80594847e-02,
           1.90709114e-01,  4.08216901e-02, -6.51613027e-02,
          -1.08826384e-02,  4.83630858e-02,  1.33542046e-01,
          -6.64243996e-02,  5.29617220e-02, -1.60631817e-02,
           7.52986670e-02,  1.28684975e-02,  7.60821700e-02,
           1.05161481e-01, -5.47739826e-02,  9.50244889e-02,
          -1.17481232e-01,  2.48524901e-02, -2.21522301e-02,
           6.47616759e-02, -3.42757441e-03,  5.14250016e-04,
           3.60398255e-02,  2.34174840e-02, -5.41116595e-02,
          -1.19185895e-01, -9.75612849e-02],
         [-1.84460077e-02,  3.08155846e-02, -1.74720094e-01,
           1.13039583e-01, -8.11213329e-02, -1.55494228e-01,
          -9.47004408e-02, -1.09828338e-01, -4.75141220e-03,
           8.48034248e-02,  5.13771735e-02, -2.58952260e-01,
          -7.79272020e-02,  2.94758510e-02,  3.08555793e-02,
           1.08934388e-01, -1.01588361e-01,  3.47666792e-03,
          -4.29731980e-03,  1.74531825e-02, -9.21818148e-03,
           1.20647073e-01, -1.41743533e-02,  2.42952108e-02,
           1.04307709e-02,  5.45765683e-02,  7.75055066e-02,
          -6.94537610e-02,  8.91614482e-02,  5.49184792e-02,
           8.38886350e-02,  7.65519217e-03]],

        [[-6.69169575e-02, -4.40144166e-02,  1.20468810e-02,
           1.82795674e-01, -2.86680683e-02, -5.84763512e-02,
           1.02223009e-02,  6.72828108e-02,  3.14529464e-02,
          -1.11310363e-01, -6.02585599e-02, -2.69603431e-01,
           8.43218062e-03,  1.31327316e-01,  1.25008821e-01,
           4.42274883e-02, -1.93066485e-02,  8.06558430e-02,
           4.02131081e-02, -3.62660550e-02,  2.78552882e-02,
           9.67296287e-02, -1.71354651e-01,  1.78433012e-03,
           4.63554934e-02,  5.10642529e-02,  1.50993299e-02,
           9.39040408e-02,  1.47469252e-01,  2.37306096e-02,
          -9.52230580e-03, -1.43197104e-01],
         [ 9.12198052e-02, -5.80615029e-02, -2.82295551e-02,
           1.02772534e-01,  3.96541879e-02, -7.91593455e-03,
          -7.86994994e-02,  1.22162580e-01,  1.00598216e-01,
          -2.16291755e-01, -9.59908939e-04, -9.82762724e-02,
           2.16343328e-01,  1.67719908e-02,  1.08334988e-01,
          -7.93664753e-02, -5.81692085e-02, -1.09599149e-02,
          -5.80202341e-02,  5.13192872e-03, -1.08037844e-01,
           2.70187408e-02,  1.28952293e-02, -8.53286535e-02,
          -3.62116238e-03,  1.16082937e-01,  9.98106003e-02,
          -1.49406176e-02,  4.21135947e-02,  8.87431428e-02,
           1.64445847e-01,  3.94322984e-02],
         [-7.22438246e-02,  2.71679386e-02,  5.53612523e-02,
           4.60421667e-03,  3.93362381e-02, -3.11845746e-02,
           3.15586552e-02, -9.62311625e-02, -6.80905730e-02,
          -6.95847422e-02,  8.27202797e-02,  8.27671289e-02,
           1.60211056e-01, -3.97183374e-02, -3.80934067e-02,
           5.79387844e-02, -2.69827433e-02, -2.91265976e-02,
          -4.56144754e-03, -8.49721432e-02, -1.47056822e-02,
          -2.21072906e-03, -3.39660160e-02,  2.93107368e-02,
          -4.12448794e-02,  1.14042424e-01,  1.88406795e-01,
           1.17986247e-01, -1.18580283e-04,  8.09077322e-02,
           9.96527970e-02,  1.18471980e-01]]],


       [[[-7.88083151e-02, -2.70568803e-02,  1.37523830e-01,
          -1.12252444e-01,  4.07482088e-02,  8.05045515e-02,
          -2.07375344e-02, -5.72510250e-03, -8.73687565e-02,
          -6.71046525e-02,  5.04024774e-02, -3.58979329e-02,
           1.84951231e-01, -1.96908731e-02,  1.12419747e-01,
          -2.35445164e-02,  9.38314348e-02, -4.06833217e-02,
          -7.06519634e-02,  9.46746618e-02, -5.57581261e-02,
          -1.24398917e-02,  1.16312653e-01, -2.97120996e-02,
           2.25771647e-02,  2.78750882e-02,  6.12738729e-03,
           6.56089745e-04,  6.96193278e-02, -6.23446051e-03,
           4.61338907e-02,  5.20423763e-02],
         [ 2.08505690e-02,  1.97942462e-02, -2.02083036e-01,
           1.27795398e-01,  1.39794007e-01, -1.85868703e-02,
           6.15841560e-02,  7.45037794e-02,  2.17709672e-02,
          -3.02003678e-02,  8.59463401e-03,  1.47979081e-01,
          -5.42613640e-02,  1.84836965e-02,  9.12852436e-02,
          -1.46334935e-02, -4.98257428e-02,  7.47414976e-02,
          -5.59075624e-02,  1.71050355e-02,  2.57489160e-02,
           4.50724363e-02, -8.00101608e-02,  1.46523193e-02,
           1.11780450e-01,  4.91655879e-02, -8.37736055e-02,
           6.80540875e-02, -6.11697286e-02, -7.14579895e-02,
          -5.03955130e-03,  6.55811056e-02],
         [ 5.02051264e-02,  6.41237050e-02, -1.13001876e-01,
           1.24183372e-01, -5.97576313e-02,  9.25169513e-02,
           7.29730204e-02,  1.45898640e-01,  1.00798994e-01,
           5.84616214e-02, -2.23423019e-02, -1.60156876e-01,
           6.91056205e-03,  2.67949551e-02,  1.64361484e-02,
          -7.34851733e-02, -6.39032349e-02, -1.08072333e-01,
           1.35105416e-01, -8.43341872e-02, -1.21737987e-01,
           2.39973664e-02,  5.49985580e-02,  4.11352366e-02,
           2.83982977e-02,  1.83836982e-01, -2.54626777e-02,
          -1.76367871e-02,  1.19340770e-01,  6.24020770e-02,
           1.27307534e-01, -9.45212692e-03]],

        [[-5.64222708e-02, -8.99318159e-02, -8.06400329e-02,
          -7.43944496e-02, -4.36185077e-02,  2.32505128e-02,
          -5.98862544e-02,  2.12376744e-01,  1.79108024e-01,
           7.89614022e-02,  7.20256846e-03,  8.22083205e-02,
          -9.18632969e-02, -1.08017199e-01,  5.89968786e-02,
          -2.33706743e-01, -1.24738932e-01,  5.55304401e-02,
           7.95798153e-02,  1.04372911e-01, -1.82877764e-01,
           6.96355551e-02,  1.23675935e-01, -9.61167365e-02,
           9.39587876e-02,  7.78261423e-02, -5.17204180e-02,
          -1.13345966e-01, -1.70647264e-01,  4.13455069e-02,
           3.61171328e-02, -1.46629244e-01],
         [ 5.85430115e-02, -1.94388255e-02, -1.01508878e-01,
          -1.25568837e-01,  4.81150970e-02,  3.19971219e-02,
           1.33625567e-01, -7.63302520e-02, -7.45719019e-03,
           1.88602254e-01, -3.13827246e-02,  2.27082223e-02,
          -8.61057192e-02,  1.68255940e-02,  2.60188058e-02,
          -5.46738654e-02, -8.73944089e-02,  7.47164786e-02,
           1.15083247e-01, -1.72333986e-01,  8.82230625e-02,
           1.01829462e-01, -1.23289429e-01,  6.77730702e-03,
           7.41358697e-02, -5.05632907e-02,  5.12504280e-02,
          -2.91965529e-02, -1.36112161e-02, -1.43037532e-02,
           1.25268042e-01,  1.20173857e-01],
         [-3.63987684e-02,  1.39704138e-01,  1.70317084e-01,
          -8.68536085e-02,  6.36992753e-02,  1.54711723e-01,
          -9.27246436e-02, -7.05991462e-02,  1.35089383e-01,
           6.31932244e-02, -2.11257935e-02,  9.82766449e-02,
          -9.32399854e-02, -9.58999842e-02,  5.20291850e-02,
          -1.21144526e-01,  7.87455291e-02, -6.08184487e-02,
           5.08782975e-02,  1.04520526e-02,  7.77358040e-02,
           1.79556593e-01,  6.07591830e-02,  6.90777004e-02,
          -7.33615905e-02, -6.81380555e-02, -1.89921297e-02,
           2.47650757e-03, -2.99216192e-02,  6.79768026e-02,
          -1.43714130e-01,  2.52959788e-01]],

        [[-1.07735634e-01,  5.16080037e-02, -6.44727349e-02,
          -5.97424768e-02,  6.94843307e-02,  1.04077369e-01,
           1.86039004e-02,  3.58665809e-02,  7.42164254e-02,
          -1.33000370e-02,  9.12712216e-02,  7.08956122e-02,
          -5.18525206e-02,  7.41134584e-03,  5.62401041e-02,
          -4.17779312e-02, -1.99549049e-02, -1.57526310e-03,
          -2.63830051e-02, -7.99752027e-03,  8.00526589e-02,
          -9.48705077e-02, -1.01754628e-01,  5.36736064e-02,
           3.48245241e-02,  6.70869052e-02, -2.55196467e-02,
          -1.54122993e-01,  2.77513266e-02,  7.54405139e-03,
           9.73728001e-02,  1.65470988e-01],
         [-2.55261287e-02,  2.12466806e-01, -5.62560558e-02,
           7.95678049e-02,  8.44097659e-02,  7.90032819e-02,
           4.31019664e-02, -1.70329303e-01, -1.34000361e-01,
           4.94322479e-02,  9.26673859e-02, -3.64340134e-02,
           1.68589950e-01,  8.18910226e-02,  3.70058790e-02,
           9.18785781e-02, -3.95624787e-02, -6.70170262e-02,
          -5.39948121e-02,  7.50692859e-02,  3.19691785e-02,
           5.16574308e-02,  2.40990128e-02,  8.11856356e-04,
           3.64203490e-02, -9.32014510e-02,  1.03231415e-01,
           1.57076214e-03, -1.09529011e-02, -1.62525568e-02,
           6.29844517e-02, -9.19183940e-02],
         [-1.05814189e-02,  9.45167243e-02, -3.15674655e-02,
          -8.89440253e-03,  3.02619487e-02,  7.70318508e-02,
          -7.03146011e-02,  5.78253232e-02, -5.30664623e-02,
           1.60122402e-02, -1.24141604e-01,  1.29941970e-01,
          -1.10244326e-01, -1.11407563e-02, -3.07260677e-02,
           5.69983199e-02,  7.57534355e-02,  3.43981683e-02,
          -8.45117867e-02,  1.08394377e-01,  1.64103508e-02,
           6.19174354e-03, -9.02684405e-03, -6.74183816e-02,
           3.58748399e-02,  3.18212109e-03,  4.71561104e-02,
          -1.38608515e-02, -5.37614748e-02,  4.25432138e-02,
           4.92697172e-02, -2.94462703e-02]]],


       [[[-5.93316071e-02, -2.39971112e-02,  2.52167210e-02,
          -2.82554813e-02,  2.61735842e-02, -1.11114215e-02,
          -2.61208173e-02, -7.32685998e-02,  3.54557112e-02,
           9.09625292e-02, -9.93428677e-02, -8.37019607e-02,
           1.29010826e-02, -8.69250000e-02,  1.05376050e-01,
          -7.21684620e-02,  4.49687950e-02,  2.42953002e-02,
          -1.14127770e-01, -4.07854207e-02,  9.28924382e-02,
          -4.44027781e-02, -1.61818303e-02,  4.34527844e-02,
           1.30586565e-01, -1.20386872e-02, -5.48143052e-02,
           4.41650972e-02,  3.59570235e-02,  1.20780312e-01,
          -7.49008805e-02,  4.09720242e-02],
         [-1.24467365e-01, -2.89576463e-02,  6.48424355e-03,
          -4.70901057e-02,  4.91554439e-02,  8.32178146e-02,
           1.14541166e-01,  1.17103241e-01,  9.10660625e-02,
           1.35509700e-01,  1.76280424e-01,  3.21200937e-02,
           1.87921885e-03,  6.38007298e-02, -4.37540561e-02,
          -2.49459632e-02, -3.78268063e-02, -1.59659190e-03,
          -2.72769015e-02,  1.64385065e-02,  5.13620153e-02,
           9.75567698e-02, -3.94818075e-02, -8.48582909e-02,
          -3.96214500e-02, -1.04857236e-01,  7.39568770e-02,
           4.27005216e-02, -1.31327391e-01,  3.33992764e-02,
          -5.38747571e-03,  2.45229788e-02],
         [ 1.16548285e-01,  1.08249858e-02,  5.49159013e-02,
          -5.41210687e-03, -1.21604159e-01, -1.17288850e-01,
          -7.39398897e-02, -9.23966020e-02, -7.70841166e-02,
           5.29533327e-02,  9.35514923e-03, -1.88379642e-03,
          -2.08182745e-02, -9.90715548e-02,  1.22506112e-01,
          -4.48893718e-02,  1.28628224e-01,  3.98237407e-02,
          -2.28272714e-02, -8.28986317e-02, -3.74484807e-02,
           1.28400892e-01, -2.12058574e-01, -9.13188756e-02,
          -1.46434531e-02, -2.48888566e-04, -1.33160502e-02,
           9.81553420e-02,  8.83238465e-02,  3.98953483e-02,
           1.38972312e-01, -1.11458138e-01]],

        [[ 8.34612250e-02,  8.23978242e-03, -4.23857421e-02,
           8.30509737e-02,  1.33784235e-01, -3.11321225e-02,
           4.33702134e-02, -4.17867824e-02, -2.56896447e-02,
           2.36436706e-02,  9.77814104e-03,  1.23384766e-01,
          -8.73546451e-02,  4.11472619e-02, -1.05833493e-01,
          -2.83193775e-02,  7.78136700e-02,  1.74447864e-01,
          -1.01883769e-01, -1.61839336e-01,  6.71362355e-02,
          -5.97722363e-03,  3.56987156e-02,  3.60365212e-02,
           2.07809284e-02,  3.31544578e-02, -6.52987137e-02,
           1.69301271e-01,  6.55270461e-03,  6.11073971e-02,
           1.31530270e-01, -1.10454403e-01],
         [ 8.54197443e-02, -9.44197830e-03,  1.55385388e-02,
           9.18071419e-02, -6.02175854e-02,  2.21655853e-02,
          -2.42546946e-02,  6.32169694e-02,  6.56450838e-02,
          -1.80364609e-01, -8.53209645e-02, -7.24718720e-02,
          -4.30286489e-02,  1.59761310e-01, -1.13069534e-01,
           6.26907647e-02, -1.17155753e-01, -3.68211381e-02,
           1.65390998e-01, -4.29485254e-02, -1.03716925e-01,
          -1.13304973e-01,  1.57183513e-01,  5.03340475e-02,
           1.89397931e-01, -8.19024667e-02,  3.66525352e-02,
           8.75892565e-02, -4.23334837e-02, -4.79933918e-02,
           6.36703074e-02,  1.01736367e-01],
         [ 1.63355656e-02,  3.46475616e-02,  9.67358053e-02,
           1.38066322e-01, -1.40040845e-01, -6.25296831e-02,
          -5.08760773e-02, -9.49853659e-02, -1.30229980e-01,
          -2.26600580e-02, -5.66076189e-02,  1.23604499e-01,
          -1.04787022e-01,  2.11787343e-01, -1.03166252e-02,
          -1.69428661e-02,  9.57470480e-03, -5.70348315e-02,
          -1.07506132e-02, -1.46737084e-01, -5.14335297e-02,
          -6.21222183e-02,  1.60990432e-02, -6.51152357e-02,
          -1.43044680e-01,  1.77712590e-02, -4.77514230e-04,
          -8.50946531e-02,  1.84209585e-01,  1.21364802e-01,
          -9.32633132e-02,  1.21458575e-01]],

        [[-4.63456940e-03,  4.97302078e-02, -1.17327712e-01,
          -8.26758295e-02, -3.71760204e-02,  1.35298356e-01,
           2.81693451e-02,  1.01745263e-01, -7.74181709e-02,
           3.71821574e-03, -5.11108302e-02,  1.97419245e-02,
           9.84246433e-02,  4.66279984e-02,  3.93141322e-02,
          -3.74092944e-02, -5.06034307e-02,  6.42646290e-03,
          -7.16049969e-03, -2.65458575e-03,  7.26206899e-02,
          -1.18110925e-01, -3.91747132e-02, -1.46794245e-02,
          -9.12510008e-02,  3.53837311e-02,  2.87574995e-03,
          -1.68177158e-01,  1.39379412e-01, -4.91012260e-02,
           1.26413241e-01,  6.35628477e-02],
         [-1.13558136e-02, -6.22803671e-03,  4.30816077e-02,
           9.64614302e-02,  1.13200992e-01, -3.15864235e-02,
          -7.42615610e-02,  6.47366866e-02,  1.92719698e-02,
           2.38852110e-02, -2.26377090e-03,  1.25062555e-01,
          -5.49151078e-02, -4.14474830e-02,  6.18971661e-02,
           7.14593977e-02,  3.15842330e-02,  2.72816941e-02,
           5.86029738e-02,  4.76243272e-02,  3.84966433e-02,
           1.82623476e-01, -8.09644461e-02,  6.52065128e-02,
          -3.78211886e-02,  1.41576231e-01, -2.23831944e-02,
          -1.46502823e-01, -6.18719906e-02,  2.69623171e-03,
           1.82879746e-01, -1.51213825e-01],
         [ 4.26518172e-02,  5.76448403e-02,  6.69016391e-02,
           1.60158309e-03,  5.22816032e-02, -9.85914916e-02,
           9.13211554e-02, -1.62314232e-02,  1.17090464e-01,
          -3.90039943e-02, -1.19164065e-01,  1.96094755e-02,
           1.24692932e-01,  4.23636250e-02,  1.31882414e-01,
          -7.77089596e-02,  2.12395005e-02,  7.93623105e-02,
          -5.08516096e-02, -4.70298808e-03,  7.95609877e-02,
           2.65830100e-01,  6.52853400e-02,  3.46363932e-02,
           6.91674203e-02,  3.53967994e-02,  9.77789909e-02,
           1.10223427e-01, -3.13314679e-03,  3.55999693e-02,
          -1.40728280e-01, -4.56514508e-02]]]], dtype=float32)>: ['efficientnetv2-b0/stem_1/conv2d/kernel']
    <tf.Variable 'efficientnetv2-b0/stem_1/tpu_batch_normalization/gamma:0' shape=(32,) dtype=float32, numpy=
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)>: ['efficientnetv2-b0/stem_1/tpu_batch_normalization/gamma']
    <tf.Variable 'efficientnetv2-b0/stem_1/tpu_batch_normalization/beta:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>: ['efficientnetv2-b0/stem_1/tpu_batch_normalization/beta']
    <tf.Variable 'efficientnetv2-b0/stem_1/tpu_batch_normalization/moving_mean:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>: ['efficientnetv2-b0/stem_1/tpu_batch_normalization/moving_mean']
    <tf.Variable 'efficientnetv2-b0/stem_1/tpu_batch_normalization/moving_variance:0' shape=(32,) dtype=float32, numpy=
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)>: ['efficientnetv2-b0/stem_1/tpu_batch_normalization/moving_variance']
    <tf.Variable 'efficientnetv2-b0/head_1/conv2d/kernel:0' shape=(1, 1, 192, 1280) dtype=float32, numpy=
array([[[[ 5.0990075e-02,  1.2878863e-02,  1.4052320e-02, ...,
          -1.3023135e-02, -1.4834874e-02,  2.2386145e-02],
         [-2.0452835e-02, -4.8361301e-02, -6.3204933e-03, ...,
           1.5227088e-02, -1.8213758e-02, -6.1055785e-03],
         [-3.4314532e-02,  1.9697867e-02,  3.3295243e-03, ...,
           1.9168353e-02,  5.0424486e-02, -8.1957158e-05],
         ...,
         [ 5.3929683e-02, -7.6894365e-02, -7.9805166e-02, ...,
           1.6627042e-02, -2.1647114e-02,  1.4510417e-02],
         [ 3.6097918e-02,  6.3360378e-02, -3.6715385e-02, ...,
           8.7231221e-03,  4.9110264e-02, -6.2803015e-02],
         [-3.1417774e-03,  5.2570004e-02, -1.2642511e-02, ...,
          -8.3061447e-03, -2.5047302e-02, -1.2373530e-02]]]],
      dtype=float32)>: ['efficientnetv2-b0/head_1/conv2d/kernel']
    <tf.Variable 'efficientnetv2-b0/head_1/tpu_batch_normalization/gamma:0' shape=(1280,) dtype=float32, numpy=array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)>: ['efficientnetv2-b0/head_1/tpu_batch_normalization/gamma']
    <tf.Variable 'efficientnetv2-b0/head_1/tpu_batch_normalization/beta:0' shape=(1280,) dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>: ['efficientnetv2-b0/head_1/tpu_batch_normalization/beta']
    <tf.Variable 'efficientnetv2-b0/head_1/tpu_batch_normalization/moving_mean:0' shape=(1280,) dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>: ['efficientnetv2-b0/head_1/tpu_batch_normalization/moving_mean']
    <tf.Variable 'efficientnetv2-b0/head_1/tpu_batch_normalization/moving_variance:0' shape=(1280,) dtype=float32, numpy=array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)>: ['efficientnetv2-b0/head_1/tpu_batch_normalization/moving_variance']

In [3]:
model.summary()
tf.keras.layers.Reshape(x,(None, None, None, 1000 ))

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
stem (Stem)                  multiple                  992       
_________________________________________________________________
blocks_0 (FusedMBConvBlock)  multiple                  4672      
_________________________________________________________________
blocks_1 (FusedMBConvBlock)  multiple                  11648     
_________________________________________________________________
blocks_2 (FusedMBConvBlock)  multiple                  41600     
_________________________________________________________________
blocks_3 (FusedMBConvBlock)  multiple                  43712     
_________________________________________________________________
blocks_4 (FusedMBConvBlock)  multiple                 

In [6]:
m2 = tf.keras.applications.InceptionV3(
                include_top=False,
                weights="imagenet",
                input_tensor=None,
                input_shape=None,
                pooling=None,
                classes=1000,
                classifier_activation="softmax")

In [7]:
m2.summary()

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, None, None, 3 864         input_3[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, None, None, 3 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, None, None, 3 0           batch_normalization[0][0]        
_______________________________________________________________________________________

In [10]:
from megazord.efficientnet.efficientnet.tfkeras import EfficientNetB0

m3 =  EfficientNetB0(weights='imagenet', include_top=False)


In [11]:
m3.summary()


Model: "efficientnet-b0"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
stem_conv (Conv2D)              (None, None, None, 3 864         input_4[0][0]                    
__________________________________________________________________________________________________
stem_bn (BatchNormalization)    (None, None, None, 3 128         stem_conv[0][0]                  
__________________________________________________________________________________________________
stem_activation (Activation)    (None, None, None, 3 0           stem_bn[0][0]                    
____________________________________________________________________________________